
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies with pnpm (using Corepack)...
      - corepack enable
      - corepack prepare pnpm@10.18.0 --activate
      - pnpm install --frozen-lockfile

  build:
    commands:
      - echo Building the React app ...
      - pnpm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no

